version: "3.8"

services:
  nembackend:
    container_name: nembackend
    image: node:latest
    tty: true
    working_dir: /home/node/app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/home/node/app
    networks:
      - nem-backend
    depends_on: 
      - nemmongodb
    command: /bin/bash -c "usermod -u `stat -c '%u' package.json` node && groupmod -g `stat -c '%g' package.json` node && su node -c 'npm install && npm run dev'"
  nemfrontend:
    container_name: nemfrontend
    image: node:latest
    working_dir: /home/node/app
    volumes:
      - ./frontend-angular:/home/node/app
    command: /bin/bash -c "usermod -u `stat -c '%u' .` node && groupmod -g `stat -c '%g' .` node && su node -c 'npm install && npm run dev'"
  nemmongodb:
    container_name: nemmongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./backend/data:/data/db
    networks:
      - nem-backend
networks:
  nem-backend:
