version: "3.8"

services:
  nembackend:
    container_name: nembackend
    env_file:
      - .env
    build:
      context: .
      target: backend
    tty: true
    working_dir: /usr/app
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    networks:
      - nem-network
    depends_on: 
      - nemmongodb
  nemfrontend:
    container_name: nemfrontend
    env_file:
      - .env
    build:
      context: .
      target: frontend
    tty: true
    working_dir: /usr/app
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    networks:
      - nem-network
  nemmongodb:
    container_name: nemmongo
    env_file:
      - .env
    build:
      context: .
      target: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - nem-network
networks:
  nem-network: